# Generated by Django 4.2.7 on 2024-07-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakomon', '0002_alter_category_options_alter_exam_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='kakomon.tag'),
        ),
    ]
