# Generated by Django 4.2.7 on 2024-07-25 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kakomon', '0003_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='kakomon.category'),
            preserve_default=False,
        ),
    ]
